[project]
name = "itf-robocon-2025"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.6",
    "numpy>=2.3.3",
]

[dependency-groups]
dev = ["ruff>=0.13.1"]

[tool.pyright]
reportUnknownMemberType = false
